apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: solmakase
spec:
  selector:
    app: web
  type: LoadBalancer  # MetalLB를 이용한 LoadBalancer 설정
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

